"""Initial schema

Revision ID: 7273fedd30fd
Revises: None
Create Date: 2026-08-08 16:34:21.539405

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7273fedd30fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_job_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employmenttype'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SETUP', 'JD_ANALYZED', 'PREFERENCES_SET', 'PUBLISHED', 'MONITORING', 'EVALUATING', 'SHORTLISTED', 'CLOSED', name='campaignstatus'), nullable=False),
    sa.Column('target_shortlist_size', sa.Integer(), nullable=False),
    sa.Column('min_target_applicants', sa.Integer(), nullable=False),
    sa.Column('desired_applicants', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('auto_close_on_deadline', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_reposts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_company_name'), 'campaigns', ['company_name'], unique=False)
    op.create_table('campaign_monitoring_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('total_applications_count', sa.Integer(), nullable=False),
    sa.Column('expected_applications_count', sa.Integer(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=False),
    sa.Column('agent_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_proposed', sa.Enum('NONE', 'REPOST_JOB', 'REFRESH_JOB', 'REVISE_REQUIREMENTS', name='actionproposed'), nullable=False),
    sa.Column('status', sa.Enum('EXECUTED', 'PENDING_APPROVAL', 'REJECTED_BY_GUARDRAIL', 'DECLINED_BY_RECRUITER', name='actionstatus'), nullable=False),
    sa.Column('guardrail_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_monitoring_logs_campaign_id'), 'campaign_monitoring_logs', ['campaign_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('application_status', sa.Enum('APPLIED', 'PARSED', 'EVALUATED', 'SHORTLISTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_campaign_id'), 'candidates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_table('hiring_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('technical_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('min_experience_years', sa.Float(), nullable=False),
    sa.Column('educational_requirements', sa.JSON(), nullable=True),
    sa.Column('key_responsibilities', sa.JSON(), nullable=True),
    sa.Column('soft_skills', sa.JSON(), nullable=True),
    sa.Column('role_expectations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_profiles_campaign_id'), 'hiring_profiles', ['campaign_id'], unique=True)
    op.create_table('job_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('LINKEDIN', 'INDEED', 'COMPANY_PORTAL', 'GENERIC_WEB', name='platformtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posts_campaign_id'), 'job_posts', ['campaign_id'], unique=False)
    op.create_table('recruiter_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('skill_priorities', sa.JSON(), nullable=True),
    sa.Column('experience_weights', sa.JSON(), nullable=True),
    sa.Column('evaluation_weights', sa.JSON(), nullable=True),
    sa.Column('evidence_sources', sa.JSON(), nullable=True),
    sa.Column('min_cgpa', sa.Float(), nullable=True),
    sa.Column('immediate_joiner_only', sa.Boolean(), nullable=False),
    sa.Column('work_authorization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_preferences_campaign_id'), 'recruiter_preferences', ['campaign_id'], unique=True)
    op.create_table('candidate_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('screening_strategy', sa.Enum('HYBRID', 'SEMANTIC', 'WEIGHTED', 'KEYWORD', 'EVIDENCE', name='screeningstrategy'), nullable=False),
    sa.Column('overall_match_score', sa.Float(), nullable=False),
    sa.Column('skill_match_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('portfolio_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_shortlisted', sa.Boolean(), nullable=False),
    sa.Column('key_strengths', sa.JSON(), nullable=True),
    sa.Column('potential_concerns', sa.JSON(), nullable=True),
    sa.Column('summary_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_evaluations_campaign_id'), 'candidate_evaluations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_candidate_evaluations_candidate_id'), 'candidate_evaluations', ['candidate_id'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('parsed_education', sa.JSON(), nullable=True),
    sa.Column('parsed_skills', sa.JSON(), nullable=True),
    sa.Column('parsed_work_experience', sa.JSON(), nullable=True),
    sa.Column('parsed_projects', sa.JSON(), nullable=True),
    sa.Column('portfolio_insights', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_candidate_id'), 'candidate_profiles', ['candidate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profiles_candidate_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_candidate_evaluations_candidate_id'), table_name='candidate_evaluations')
    op.drop_index(op.f('ix_candidate_evaluations_campaign_id'), table_name='candidate_evaluations')
    op.drop_table('candidate_evaluations')
    op.drop_index(op.f('ix_recruiter_preferences_campaign_id'), table_name='recruiter_preferences')
    op.drop_table('recruiter_preferences')
    op.drop_index(op.f('ix_job_posts_campaign_id'), table_name='job_posts')
    op.drop_table('job_posts')
    op.drop_index(op.f('ix_hiring_profiles_campaign_id'), table_name='hiring_profiles')
    op.drop_table('hiring_profiles')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_campaign_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_campaign_monitoring_logs_campaign_id'), table_name='campaign_monitoring_logs')
    op.drop_table('campaign_monitoring_logs')
    op.drop_index(op.f('ix_campaigns_company_name'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
